Fixed runExamples in ResolventModes/SSRM

diff --git a/ResolventModes/SSRM/runExample b/ResolventModes/SSRM/runExample
--- a/ResolventModes/SSRM/runExample
+++ b/ResolventModes/SSRM/runExample
@@ -1,12 +1,19 @@
 #!/bin/bash
 
-./importLibs
+./importLibs 
 
-makenek Nek_SSRM
+makenek Nek_SSRM || { 
+    echo "Error compiling..." 
+    exit 1
+}
 
-genmap <<
-channel_2D
+genmap <<< 'channel_2D
 
-<< EOF
+
+' || { 
+    echo "Error creating map file..." 
+    exit 1
+}
+
 
 ./runArnoldi channel_2D 2 0 10 
